### ISSUE TITLE
Without attendees while creating events, Error is getting.

### ISSUE THREAD

**Issue by libindstme** [lakshmanaprabhu/manage_calendar_events#31]
PlatformException(error, Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.addAttendees(ManageCalendarEventsPlugin.java:177)
	at com.fantastic.manage_calendar_events.ManageCalendarEventsPlugin.onMethodCall(ManageCalendarEventsPlugin.java:133)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
)

**Comment by itb55** [comment]
yes, the same problem!

It should be at least: 

`attendees: Attendees(attendees: [])`

**Comment by ErnestoCuesy** [comment]
@itb55 thanks, that helped.
