### ISSUE TITLE
plugin not working on release mode(Android)

### ISSUE THREAD

**Issue by libindstme** [lakshmanaprabhu/manage_calendar_events#6]
2021-04-06 09:47:28.005 11669-11684/? D/CalP:D:PrivacyHelper: checkAndClearSyncFields(): Gdpr Permission granted. Skip clearing fields
2021-04-06 09:47:28.010 11669-11684/? I/CalP:D:AlarmManager: rescheduleMissedAlarms()
2021-04-06 09:47:28.013 11317-11355/? I/flutter: NoSuchMethodError: The method 'contains' was called on null.
2021-04-06 09:47:28.013 11317-11355/? I/flutter: Receiver: null
2021-04-06 09:47:28.013 11317-11355/? I/flutter: Tried calling: contains()
2021-04-06 09:47:28.014 11669-11684/? V/CalP:D:CalendarProvider2: query uri - content://com.android.calendar/calendar_alerts
2021-04-06 09:47:28.023 11317-11355/? I/flutter: #0      CalendarLis.build.<anonymous closure> (package:vowcrm/user/activity/event_calendar_list.dart:118)
2021-04-06 09:47:28.023 11317-11355/? I/flutter: #1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:773)
2021-04-06 09:47:28.023 11317-11355/? I/flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4684)
2021-04-06 09:47:28.023 11317-11355/? I/flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4567)
2021-04-06 09:47:28.023 11317-11355/? I/flutter: #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4739)

**Comment by libindstme** [comment]
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 2.1.0-12.1.pre at C:\Flutter\flutter
    • Framework revision 8264cb3e8a (4 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by joseucarvajal** [comment]
Any progress on this?

**Comment by jiazeh** [comment]
same issue.
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by lakshmanaprabhu** [comment]
Fixed the Android release mode issue on version 1.06. 
Kindly verify and share your thoughts.
